---

## adding by ansible

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # put latest release tag from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:

      - id: check-added-large-files
        name: Check for large files added
        description: Prevents giant files from being committed
        args:
          - --maxkb=1000

      - id: check-json
        name: Check json files syntax
        description: Verifies json files syntax

      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Checks for files that contain merge conflict strings

      - id: check-symlinks
        name: Check for broken symlinks
        description: Checks for symlinks which do not point to anything

      - id: check-toml
        name: Check toml files syntax
        description: Verifies TOML files syntax

      - id: check-xml
        name: Check xml files syntax
        description: Verifies xml files syntax

      - id: check-yaml
        name: Check yaml files syntax
        description: Verifies yaml files syntax
        exclude: component.yml|.gitlab-ci.yml

      - id: detect-private-key
        name: Detect for private keys added
        description: Checks for the existence of private keys

      - id: double-quote-string-fixer
        name: Fix double quote strings
        description: Replaces double quoted strings with single quoted strings
        exclude: .py

      - id: end-of-file-fixer
        name: Fix end-of-file
        description: Makes sure files end in a newline and only a newline

      - id: no-commit-to-branch
        name: Prevent commits to main/master branches
        description: Protects main and master branches from direct checkins

      - id: pretty-format-json
        name: Check for pretty json format
        description: Checks that all your JSON files are pretty
        args:
          - --autofix
          - --indent=2

      - id: requirements-txt-fixer
        name: Sort requirements.txt file
        description: Sorts entries in requirements.txt

      - id: sort-simple-yaml
        name: Sort simple yaml files
        description: Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks

      - id: trailing-whitespace
        name: Trim trailing whitespaces
        description: Trims trailing whitespace
        args:
          - --markdown-linebreak-ext=md




exclude: ^data
